---
title: "new things"
author: "Grace Lawley"
date: "8/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# New things

Testing age FLOORED
```{r}
testing_floor <- kuczaj_nrc %>% 
  mutate(age_years_floor = floor(age_years),
         age_months_floor = floor(age_months)) %>% 
  arrange(age_months_floor)
  
# number transcript for each age_months_floor
testing_floor <- testing_floor %>% 
  group_by(age_months_floor) %>% 
  mutate(n_transcripts = n_distinct(transcript_id)) %>% 
  ungroup()

testing_floor %>% 
  filter(sentiment == "joy") %>% 
  #ggplot(aes(x = age_months_floor)) +
  #ggplot(aes(x = age_months_floor, weights = 1/n_transcripts)) +
  ggplot(aes(x = age_months_floor, weights = n_transcripts/sum(n_transcripts))) +
    geom_density()


testing_floor %>%
  filter(!sentiment %in% c("positive", "negative")) %>%
  ggplot(aes(x = age_months_floor, fill = sentiment, weights = 1/n_transcripts)) +
    geom_histogram() +
    facet_wrap(~ sentiment)

testing_floor %>%
  filter(!sentiment %in% c("positive", "negative")) %>%
  ggplot(aes(x = age_months_floor, fill = sentiment)) +
    geom_histogram() +
    facet_wrap(~ sentiment)

```


Testing age ROUNDED
```{r}
testing_round <- kuczaj_nrc %>% 
  mutate(age_years_round = round(age_years),
         age_months_round = round(age_months)) %>% 
  arrange(age_months_round)


# number transcripts for each age_months_round level
testing_round <- testing_round %>% 
  group_by(age_months_round) %>% 
  mutate(n_transcripts = n_distinct(transcript_id)) %>% 
  ungroup()
```

Number of transcripts that now have less than 50 words
```{r}
kuczaj_nrc %>% 
  distinct(transcript_id, n) %>% 
  count(n < 50)
```

Min N: `r min(kuczaj_nrc$n)`
Max N: `r max(kuczaj_nrc$n)`
Median N: `r median(kuczaj_nrc$n)`
Mean N: `r mean(kuczaj_nrc$n)`
SD N: `r sd(kuczaj_nrc$n)`

Sampling WITH replacement and n = 50:
```{r}
# sample_100_wr <- kuczaj_nrc %>% 
#   filter(n >= 50) %>% 
#   group_by(transcript_id) %>% 
#   sample_n(size = 100, replace = TRUE)
```

How are the transcripts distributed across age?


Sampling WITHOUT replacement and n = 50:
```{r}
# foo <- kuczaj_nrc %>% 
#   mutate(age_year_floor = floor(age_years),
#          age_month_floor = floor(age_months))  
# 
# 
# age_floor_count <- foo %>% 
#   count(age_year_floor, age_month_floor) 
# 
# 
# 
# 
# ggplot(age_floor, aes(age_month_floor, n, group = as.factor(age_year_floor), color = as.factor(age_year_floor))) +
#   geom_point() +
#   geom_line()
  

  
```

