---
title: "Kuczaj Corpus Sentiment Analysis, Part 2"
author: "Grace Lawley"
date: "8/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 6)
```

```{r loading packages, warning = FALSE, message = FALSE}
library(tidyverse)
library(tidytext)
library(forcats)
library(skimr)
```


```{r loading data}
sentiments <- read_csv("data/kuczaj_nrc.csv")     

glimpse(sentiments)
```

Filtering for the same 6 sentiments as before but this time making sentiment an ordered factor
```{r}
sentiment_levels <- c("trust", "joy", "anticipation", 
                      "sadness", "fear", "anger")

sentiments <- sentiments %>% 
  select(-age_years, -word) %>% 
  filter(sentiment %in% sentiment_levels) %>% 
  mutate(sentiment = factor(sentiment, levels = sentiment_levels))
```

Since there are only partial observations for the first and last month, removing them:
```{r}
sentiments <- sentiments %>% 
  filter(age_months >= 29 & age_months <= 60)
```


```{r}
sentiments2 <- sentiments %>% 
  add_count(age_months, sentiment) %>% 
  rename(n_sentiment = n) %>% 
  distinct(age_months, sentiment, .keep_all = TRUE)


# Adding in count for total tokens per transcript that were kept
sentiments2 <- sentiments2 %>% 
  group_by(age_months) %>% 
  mutate(n_tokens = sum(n_sentiment)) %>% 
  ungroup()

skim(sentiments2)
```


```{r}
aux <- sentiments2 %>% 
  tidyr::expand(nesting(age_months, n_tokens), sentiment)

sentiments2 <- aux %>% 
  left_join(sentiments2, by = c("age_months", "n_tokens", "sentiment")) %>% 
  replace_na(list(n_sentiment = 0))


sentiments2 <- sentiments2 %>% 
  mutate(percent = n_sentiment/n_tokens)
  
```

# Plot 1
```{r}
ggplot(sentiments2, aes(age_months, percent, color = sentiment)) +
  geom_point(alpha = 0.7) +
  facet_wrap(~ sentiment) + 
  labs(x = "Age (months)", y = "Percent") +
  guides(color = FALSE) +
  theme_minimal()
```

# Trying age binned this time
```{r}
ages_binned <- sentiments %>% 
  mutate(age_months = floor(age_months)) 

ages_binned <- ages_binned %>% 
  add_count(age_months, sentiment) %>% 
  rename(n_sentiment = n) %>% 
  distinct(age_months, sentiment, .keep_all = TRUE)


# Adding in count for total tokens per transcript that were kept
ages_binned <- ages_binned %>% 
  group_by(age_months) %>% 
  mutate(n_tokens = sum(n_sentiment)) %>% 
  ungroup()

skim(ages_binned)
```


```{r}
aux2 <- ages_binned %>% 
  tidyr::expand(nesting(age_months, n_tokens), sentiment)

ages_binned2 <- aux2 %>% 
  left_join(ages_binned, by = c("age_months", "n_tokens", "sentiment")) %>% 
  replace_na(list(n_sentiment = 0))


ages_binned2 <- ages_binned2 %>% 
  mutate(percent = n_sentiment/n_tokens)
```

Adding in a column for positive and negative groups
```{r}
ages_binned2 <- ages_binned2 %>% 
  mutate(type = ifelse(sentiment %in% c("trust", "joy", "anticipation"), 
                       "positive", "negative"))

```

# Plot 2
```{r}
ggplot(ages_binned2, aes(age_months, percent, fill = sentiment)) +
  geom_col(alpha = 0.7) +
  facet_wrap(~ sentiment) + 
  labs(x = "Age (months)", y = "Percent", title = "Ages binned") +
  guides(fill = FALSE) +
  theme_minimal()

ggplot(ages_binned2, aes(age_months, percent, fill = sentiment)) +
  geom_col(alpha = 0.7) +
  facet_grid(sentiment ~ .)+
  labs(x = "Age (months)", y = "Percent", title = "Ages binned") +
  guides(fill = FALSE) +
  theme_minimal()
```



```{r}
library(egg)

positive_plot <- ages_binned2 %>% 
  filter(type == "positive") %>% 
  ggplot(aes(age_months, percent, fill = sentiment)) +
    geom_col(alpha = 0.7) +
    facet_wrap(~sentiment, ncol = 1) +
    geom_vline(xintercept = c(36, 48), color = "black") +
    geom_vline(xintercept = c(29, 59), color = "black", linetype = "dotted") +
    # changing appearance
    theme_minimal() +
    labs(x = "", y = "") +
    guides(fill = FALSE) +
    scale_fill_manual(values = c("#21132B", "#4F406E", "#6C7399")) +
    scale_y_continuous(breaks = c(0.05, 0.15, 0.25),
                       labels = c("5%", "15%", "25%")) +
    scale_x_continuous(breaks = c(29, 36, 48, 59),
                       labels = c("2.4 yrs", "3 yrs", "4 yrs", "4.9 yrs")) +
    theme(strip.text = element_text(size = 13, face = "italic"),
          axis.text.x = element_text(face = "italic"),
          axis.text.y = element_text(face = "italic"))


negative_plot <- ages_binned2 %>% 
  filter(type == "negative") %>% 
  ggplot(aes(age_months, percent, fill = sentiment)) +
    geom_col(alpha = 0.7) +
    facet_wrap(~sentiment, ncol = 1) +
    geom_vline(xintercept = c(36, 48), color = "black") +
    geom_vline(xintercept = c(29, 59), color = "black", linetype = "dotted") +
    # changing apperance
    theme_minimal() +
    labs(x = "", y = "") +
    guides(fill = FALSE) +
    scale_fill_manual(values = c("#97B8C7", "#AEC9C3", "#7FCCD3")) +
    scale_y_continuous(breaks = c(0.05, 0.15, 0.25),
                       labels = c("5%", "15%", "25%")) +
    scale_x_continuous(breaks = c(29, 36, 48, 59),
                       labels = c("2.4 yrs", "3 yrs", "4 yrs", "4.9 yrs")) +
    theme(strip.text = element_text(size = 13, face = "italic"),
          axis.text.x = element_text(face = "italic"),
          axis.text.y = element_text(face = "italic"))

ggarrange(positive_plot, negative_plot, ncol = 2, nrow = 1)

```

# Same plot but opposite layout
```{r}

ggplot(ages_binned2, aes(age_months, percent, fill = sentiment)) +
  geom_col(alpha = 0.7) +
  facet_wrap(~ sentiment, scales = "free_x") + 
  geom_vline(xintercept = c(36, 48), color = "black") +
  geom_vline(xintercept = c(29, 59), color = "black", linetype = "dotted") +
  theme_minimal() +
  labs(x = "", y = "") +
  guides(fill = FALSE) +
  scale_fill_manual(values = c("#21132B", "#4F406E", "#6C7399",
                               "#97B8C7", "#AEC9C3", "#7FCCD3")) +
  scale_y_continuous(breaks = c(0.05, 0.15, 0.25),
                     labels = c("5%", "15%", "25%")) +
  scale_x_continuous(breaks = c(29, 36, 48, 59),
                     labels = c("2.4 yrs", "3 yrs", "4 yrs", "4.9 yrs")) +
  theme(strip.text = element_text(size = 13, face = "italic"),
        axis.text.x = element_text(face = "italic"),
        axis.text.y = element_text(face = "italic"),
        panel.spacing.x = unit(1, "line"))
  
```

    
```{r}
ggplot(ages_binned2, aes(age_months, percent, color = sentiment, linetype = sentiment)) +
  #geom_point(alpha = 0.7) +
  geom_line(size = 1) +
  scale_color_manual(values = c("#21132B", "#4F406E", "#6C7399",
                               "#97B8C7", "#AEC9C3", "#7FCCD3")) +
  theme_minimal()



ggplot(ages_binned2, aes(age_months, percent, color = type)) +
  #geom_point(alpha = 0.7) +
  geom_line(aes(group = sentiment, linetype = sentiment)) +
  theme_minimal()
```





